//
//  Flag.swift
//  macflag
//
//  Created by Eric May on 6/26/22.
//

import Foundation

struct CountryFlag: Identifiable {
    let emoji: String
    let name: String
    var id: String { emoji }
}

struct FlagData {
    static let special: [CountryFlag] = [
        CountryFlag(emoji: "🏴‍☠️", name: "Pirate Flag"),
        CountryFlag(emoji: "🏳️‍🌈", name: "Pride Flag"),
        CountryFlag(emoji: "🏳️‍⚧️", name: "Transgender Pride Flag"),
        CountryFlag(emoji: "🏁", name: "Checkered Flag"),
        CountryFlag(emoji: "🚩", name: "Red Flag"),
        CountryFlag(emoji: "🎌", name: "Crossed Flags"),
        CountryFlag(emoji: "🏴", name: "Black Flag"),
        CountryFlag(emoji: "🏳️", name: "White Flag"),
    ]

    static let countries: [CountryFlag] = [
        CountryFlag(emoji: "🇦🇨", name: "Ascension Island"),
        CountryFlag(emoji: "🇦🇩", name: "Andorra"),
        CountryFlag(emoji: "🇦🇪", name: "United Arab Emirates"),
        CountryFlag(emoji: "🇦🇫", name: "Afghanistan"),
        CountryFlag(emoji: "🇦🇬", name: "Antigua & Barbuda"),
        CountryFlag(emoji: "🇦🇮", name: "Anguilla"),
        CountryFlag(emoji: "🇦🇱", name: "Albania"),
        CountryFlag(emoji: "🇦🇲", name: "Armenia"),
        CountryFlag(emoji: "🇦🇴", name: "Angola"),
        CountryFlag(emoji: "🇦🇶", name: "Antarctica"),
        CountryFlag(emoji: "🇦🇷", name: "Argentina"),
        CountryFlag(emoji: "🇦🇸", name: "American Samoa"),
        CountryFlag(emoji: "🇦🇹", name: "Austria"),
        CountryFlag(emoji: "🇦🇺", name: "Australia"),
        CountryFlag(emoji: "🇦🇼", name: "Aruba"),
        CountryFlag(emoji: "🇦🇽", name: "Åland Islands"),
        CountryFlag(emoji: "🇦🇿", name: "Azerbaijan"),
        CountryFlag(emoji: "🇧🇦", name: "Bosnia & Herzegovina"),
        CountryFlag(emoji: "🇧🇧", name: "Barbados"),
        CountryFlag(emoji: "🇧🇩", name: "Bangladesh"),
        CountryFlag(emoji: "🇧🇪", name: "Belgium"),
        CountryFlag(emoji: "🇧🇫", name: "Burkina Faso"),
        CountryFlag(emoji: "🇧🇬", name: "Bulgaria"),
        CountryFlag(emoji: "🇧🇭", name: "Bahrain"),
        CountryFlag(emoji: "🇧🇮", name: "Burundi"),
        CountryFlag(emoji: "🇧🇯", name: "Benin"),
        CountryFlag(emoji: "🇧🇱", name: "St. Barthélemy"),
        CountryFlag(emoji: "🇧🇲", name: "Bermuda"),
        CountryFlag(emoji: "🇧🇳", name: "Brunei"),
        CountryFlag(emoji: "🇧🇴", name: "Bolivia"),
        CountryFlag(emoji: "🇧🇶", name: "Caribbean Netherlands"),
        CountryFlag(emoji: "🇧🇷", name: "Brazil"),
        CountryFlag(emoji: "🇧🇸", name: "Bahamas"),
        CountryFlag(emoji: "🇧🇹", name: "Bhutan"),
        CountryFlag(emoji: "🇧🇻", name: "Bouvet Island"),
        CountryFlag(emoji: "🇧🇼", name: "Botswana"),
        CountryFlag(emoji: "🇧🇾", name: "Belarus"),
        CountryFlag(emoji: "🇧🇿", name: "Belize"),
        CountryFlag(emoji: "🇨🇦", name: "Canada"),
        CountryFlag(emoji: "🇨🇨", name: "Cocos (Keeling) Islands"),
        CountryFlag(emoji: "🇨🇩", name: "Congo - Kinshasa"),
        CountryFlag(emoji: "🇨🇫", name: "Central African Republic"),
        CountryFlag(emoji: "🇨🇬", name: "Congo - Brazzaville"),
        CountryFlag(emoji: "🇨🇭", name: "Switzerland"),
        CountryFlag(emoji: "🇨🇮", name: "Côte d'Ivoire"),
        CountryFlag(emoji: "🇨🇰", name: "Cook Islands"),
        CountryFlag(emoji: "🇨🇱", name: "Chile"),
        CountryFlag(emoji: "🇨🇲", name: "Cameroon"),
        CountryFlag(emoji: "🇨🇳", name: "China"),
        CountryFlag(emoji: "🇨🇴", name: "Colombia"),
        CountryFlag(emoji: "🇨🇵", name: "Clipperton Island"),
        CountryFlag(emoji: "🇨🇷", name: "Costa Rica"),
        CountryFlag(emoji: "🇨🇺", name: "Cuba"),
        CountryFlag(emoji: "🇨🇻", name: "Cape Verde"),
        CountryFlag(emoji: "🇨🇼", name: "Curaçao"),
        CountryFlag(emoji: "🇨🇽", name: "Christmas Island"),
        CountryFlag(emoji: "🇨🇾", name: "Cyprus"),
        CountryFlag(emoji: "🇨🇿", name: "Czechia"),
        CountryFlag(emoji: "🇩🇪", name: "Germany"),
        CountryFlag(emoji: "🇩🇬", name: "Diego Garcia"),
        CountryFlag(emoji: "🇩🇯", name: "Djibouti"),
        CountryFlag(emoji: "🇩🇰", name: "Denmark"),
        CountryFlag(emoji: "🇩🇲", name: "Dominica"),
        CountryFlag(emoji: "🇩🇴", name: "Dominican Republic"),
        CountryFlag(emoji: "🇩🇿", name: "Algeria"),
        CountryFlag(emoji: "🇪🇦", name: "Ceuta & Melilla"),
        CountryFlag(emoji: "🇪🇨", name: "Ecuador"),
        CountryFlag(emoji: "🇪🇪", name: "Estonia"),
        CountryFlag(emoji: "🇪🇬", name: "Egypt"),
        CountryFlag(emoji: "🇪🇭", name: "Western Sahara"),
        CountryFlag(emoji: "🇪🇷", name: "Eritrea"),
        CountryFlag(emoji: "🇪🇸", name: "Spain"),
        CountryFlag(emoji: "🇪🇹", name: "Ethiopia"),
        CountryFlag(emoji: "🇪🇺", name: "European Union"),
        CountryFlag(emoji: "🇫🇮", name: "Finland"),
        CountryFlag(emoji: "🇫🇯", name: "Fiji"),
        CountryFlag(emoji: "🇫🇰", name: "Falkland Islands"),
        CountryFlag(emoji: "🇫🇲", name: "Micronesia"),
        CountryFlag(emoji: "🇫🇴", name: "Faroe Islands"),
        CountryFlag(emoji: "🇫🇷", name: "France"),
        CountryFlag(emoji: "🇬🇦", name: "Gabon"),
        CountryFlag(emoji: "🇬🇧", name: "United Kingdom"),
        CountryFlag(emoji: "🇬🇩", name: "Grenada"),
        CountryFlag(emoji: "🇬🇪", name: "Georgia"),
        CountryFlag(emoji: "🇬🇫", name: "French Guiana"),
        CountryFlag(emoji: "🇬🇬", name: "Guernsey"),
        CountryFlag(emoji: "🇬🇭", name: "Ghana"),
        CountryFlag(emoji: "🇬🇮", name: "Gibraltar"),
        CountryFlag(emoji: "🇬🇱", name: "Greenland"),
        CountryFlag(emoji: "🇬🇲", name: "Gambia"),
        CountryFlag(emoji: "🇬🇳", name: "Guinea"),
        CountryFlag(emoji: "🇬🇵", name: "Guadeloupe"),
        CountryFlag(emoji: "🇬🇶", name: "Equatorial Guinea"),
        CountryFlag(emoji: "🇬🇷", name: "Greece"),
        CountryFlag(emoji: "🇬🇸", name: "South Georgia & South Sandwich Islands"),
        CountryFlag(emoji: "🇬🇹", name: "Guatemala"),
        CountryFlag(emoji: "🇬🇺", name: "Guam"),
        CountryFlag(emoji: "🇬🇼", name: "Guinea-Bissau"),
        CountryFlag(emoji: "🇬🇾", name: "Guyana"),
        CountryFlag(emoji: "🇭🇰", name: "Hong Kong SAR China"),
        CountryFlag(emoji: "🇭🇲", name: "Heard & McDonald Islands"),
        CountryFlag(emoji: "🇭🇳", name: "Honduras"),
        CountryFlag(emoji: "🇭🇷", name: "Croatia"),
        CountryFlag(emoji: "🇭🇹", name: "Haiti"),
        CountryFlag(emoji: "🇭🇺", name: "Hungary"),
        CountryFlag(emoji: "🇮🇨", name: "Canary Islands"),
        CountryFlag(emoji: "🇮🇩", name: "Indonesia"),
        CountryFlag(emoji: "🇮🇪", name: "Ireland"),
        CountryFlag(emoji: "🇮🇱", name: "Israel"),
        CountryFlag(emoji: "🇮🇲", name: "Isle of Man"),
        CountryFlag(emoji: "🇮🇳", name: "India"),
        CountryFlag(emoji: "🇮🇴", name: "British Indian Ocean Territory"),
        CountryFlag(emoji: "🇮🇶", name: "Iraq"),
        CountryFlag(emoji: "🇮🇷", name: "Iran"),
        CountryFlag(emoji: "🇮🇸", name: "Iceland"),
        CountryFlag(emoji: "🇮🇹", name: "Italy"),
        CountryFlag(emoji: "🇯🇪", name: "Jersey"),
        CountryFlag(emoji: "🇯🇲", name: "Jamaica"),
        CountryFlag(emoji: "🇯🇴", name: "Jordan"),
        CountryFlag(emoji: "🇯🇵", name: "Japan"),
        CountryFlag(emoji: "🇰🇪", name: "Kenya"),
        CountryFlag(emoji: "🇰🇬", name: "Kyrgyzstan"),
        CountryFlag(emoji: "🇰🇭", name: "Cambodia"),
        CountryFlag(emoji: "🇰🇮", name: "Kiribati"),
        CountryFlag(emoji: "🇰🇲", name: "Comoros"),
        CountryFlag(emoji: "🇰🇳", name: "St. Kitts & Nevis"),
        CountryFlag(emoji: "🇰🇵", name: "North Korea"),
        CountryFlag(emoji: "🇰🇷", name: "South Korea"),
        CountryFlag(emoji: "🇰🇼", name: "Kuwait"),
        CountryFlag(emoji: "🇰🇾", name: "Cayman Islands"),
        CountryFlag(emoji: "🇰🇿", name: "Kazakhstan"),
        CountryFlag(emoji: "🇱🇦", name: "Laos"),
        CountryFlag(emoji: "🇱🇧", name: "Lebanon"),
        CountryFlag(emoji: "🇱🇨", name: "St. Lucia"),
        CountryFlag(emoji: "🇱🇮", name: "Liechtenstein"),
        CountryFlag(emoji: "🇱🇰", name: "Sri Lanka"),
        CountryFlag(emoji: "🇱🇷", name: "Liberia"),
        CountryFlag(emoji: "🇱🇸", name: "Lesotho"),
        CountryFlag(emoji: "🇱🇹", name: "Lithuania"),
        CountryFlag(emoji: "🇱🇺", name: "Luxembourg"),
        CountryFlag(emoji: "🇱🇻", name: "Latvia"),
        CountryFlag(emoji: "🇱🇾", name: "Libya"),
        CountryFlag(emoji: "🇲🇦", name: "Morocco"),
        CountryFlag(emoji: "🇲🇨", name: "Monaco"),
        CountryFlag(emoji: "🇲🇩", name: "Moldova"),
        CountryFlag(emoji: "🇲🇪", name: "Montenegro"),
        CountryFlag(emoji: "🇲🇫", name: "St. Martin"),
        CountryFlag(emoji: "🇲🇬", name: "Madagascar"),
        CountryFlag(emoji: "🇲🇭", name: "Marshall Islands"),
        CountryFlag(emoji: "🇲🇰", name: "North Macedonia"),
        CountryFlag(emoji: "🇲🇱", name: "Mali"),
        CountryFlag(emoji: "🇲🇲", name: "Myanmar (Burma)"),
        CountryFlag(emoji: "🇲🇳", name: "Mongolia"),
        CountryFlag(emoji: "🇲🇴", name: "Macao SAR China"),
        CountryFlag(emoji: "🇲🇵", name: "Northern Mariana Islands"),
        CountryFlag(emoji: "🇲🇶", name: "Martinique"),
        CountryFlag(emoji: "🇲🇷", name: "Mauritania"),
        CountryFlag(emoji: "🇲🇸", name: "Montserrat"),
        CountryFlag(emoji: "🇲🇹", name: "Malta"),
        CountryFlag(emoji: "🇲🇺", name: "Mauritius"),
        CountryFlag(emoji: "🇲🇻", name: "Maldives"),
        CountryFlag(emoji: "🇲🇼", name: "Malawi"),
        CountryFlag(emoji: "🇲🇽", name: "Mexico"),
        CountryFlag(emoji: "🇲🇾", name: "Malaysia"),
        CountryFlag(emoji: "🇲🇿", name: "Mozambique"),
        CountryFlag(emoji: "🇳🇦", name: "Namibia"),
        CountryFlag(emoji: "🇳🇨", name: "New Caledonia"),
        CountryFlag(emoji: "🇳🇪", name: "Niger"),
        CountryFlag(emoji: "🇳🇫", name: "Norfolk Island"),
        CountryFlag(emoji: "🇳🇬", name: "Nigeria"),
        CountryFlag(emoji: "🇳🇮", name: "Nicaragua"),
        CountryFlag(emoji: "🇳🇱", name: "Netherlands"),
        CountryFlag(emoji: "🇳🇴", name: "Norway"),
        CountryFlag(emoji: "🇳🇵", name: "Nepal"),
        CountryFlag(emoji: "🇳🇷", name: "Nauru"),
        CountryFlag(emoji: "🇳🇺", name: "Niue"),
        CountryFlag(emoji: "🇳🇿", name: "New Zealand"),
        CountryFlag(emoji: "🇴🇲", name: "Oman"),
        CountryFlag(emoji: "🇵🇦", name: "Panama"),
        CountryFlag(emoji: "🇵🇪", name: "Peru"),
        CountryFlag(emoji: "🇵🇫", name: "French Polynesia"),
        CountryFlag(emoji: "🇵🇬", name: "Papua New Guinea"),
        CountryFlag(emoji: "🇵🇭", name: "Philippines"),
        CountryFlag(emoji: "🇵🇰", name: "Pakistan"),
        CountryFlag(emoji: "🇵🇱", name: "Poland"),
        CountryFlag(emoji: "🇵🇲", name: "St. Pierre & Miquelon"),
        CountryFlag(emoji: "🇵🇳", name: "Pitcairn Islands"),
        CountryFlag(emoji: "🇵🇷", name: "Puerto Rico"),
        CountryFlag(emoji: "🇵🇸", name: "Palestinian Territories"),
        CountryFlag(emoji: "🇵🇹", name: "Portugal"),
        CountryFlag(emoji: "🇵🇼", name: "Palau"),
        CountryFlag(emoji: "🇵🇾", name: "Paraguay"),
        CountryFlag(emoji: "🇶🇦", name: "Qatar"),
        CountryFlag(emoji: "🇷🇪", name: "Réunion"),
        CountryFlag(emoji: "🇷🇴", name: "Romania"),
        CountryFlag(emoji: "🇷🇸", name: "Serbia"),
        CountryFlag(emoji: "🇷🇺", name: "Russia"),
        CountryFlag(emoji: "🇷🇼", name: "Rwanda"),
        CountryFlag(emoji: "🇸🇦", name: "Saudi Arabia"),
        CountryFlag(emoji: "🇸🇧", name: "Solomon Islands"),
        CountryFlag(emoji: "🇸🇨", name: "Seychelles"),
        CountryFlag(emoji: "🇸🇩", name: "Sudan"),
        CountryFlag(emoji: "🇸🇪", name: "Sweden"),
        CountryFlag(emoji: "🇸🇬", name: "Singapore"),
        CountryFlag(emoji: "🇸🇭", name: "St. Helena"),
        CountryFlag(emoji: "🇸🇮", name: "Slovenia"),
        CountryFlag(emoji: "🇸🇯", name: "Svalbard & Jan Mayen"),
        CountryFlag(emoji: "🇸🇰", name: "Slovakia"),
        CountryFlag(emoji: "🇸🇱", name: "Sierra Leone"),
        CountryFlag(emoji: "🇸🇲", name: "San Marino"),
        CountryFlag(emoji: "🇸🇳", name: "Senegal"),
        CountryFlag(emoji: "🇸🇴", name: "Somalia"),
        CountryFlag(emoji: "🇸🇷", name: "Suriname"),
        CountryFlag(emoji: "🇸🇸", name: "South Sudan"),
        CountryFlag(emoji: "🇸🇹", name: "São Tomé & Príncipe"),
        CountryFlag(emoji: "🇸🇻", name: "El Salvador"),
        CountryFlag(emoji: "🇸🇽", name: "Sint Maarten"),
        CountryFlag(emoji: "🇸🇾", name: "Syria"),
        CountryFlag(emoji: "🇸🇿", name: "Eswatini"),
        CountryFlag(emoji: "🇹🇦", name: "Tristan da Cunha"),
        CountryFlag(emoji: "🇹🇨", name: "Turks & Caicos Islands"),
        CountryFlag(emoji: "🇹🇩", name: "Chad"),
        CountryFlag(emoji: "🇹🇫", name: "French Southern Territories"),
        CountryFlag(emoji: "🇹🇬", name: "Togo"),
        CountryFlag(emoji: "🇹🇭", name: "Thailand"),
        CountryFlag(emoji: "🇹🇯", name: "Tajikistan"),
        CountryFlag(emoji: "🇹🇰", name: "Tokelau"),
        CountryFlag(emoji: "🇹🇱", name: "Timor-Leste"),
        CountryFlag(emoji: "🇹🇲", name: "Turkmenistan"),
        CountryFlag(emoji: "🇹🇳", name: "Tunisia"),
        CountryFlag(emoji: "🇹🇴", name: "Tonga"),
        CountryFlag(emoji: "🇹🇷", name: "Turkey"),
        CountryFlag(emoji: "🇹🇹", name: "Trinidad & Tobago"),
        CountryFlag(emoji: "🇹🇻", name: "Tuvalu"),
        CountryFlag(emoji: "🇹🇼", name: "Taiwan"),
        CountryFlag(emoji: "🇹🇿", name: "Tanzania"),
        CountryFlag(emoji: "🇺🇦", name: "Ukraine"),
        CountryFlag(emoji: "🇺🇬", name: "Uganda"),
        CountryFlag(emoji: "🇺🇲", name: "U.S. Outlying Islands"),
        CountryFlag(emoji: "🇺🇳", name: "United Nations"),
        CountryFlag(emoji: "🇺🇸", name: "United States"),
        CountryFlag(emoji: "🇺🇾", name: "Uruguay"),
        CountryFlag(emoji: "🇺🇿", name: "Uzbekistan"),
        CountryFlag(emoji: "🇻🇦", name: "Vatican City"),
        CountryFlag(emoji: "🇻🇨", name: "St. Vincent & Grenadines"),
        CountryFlag(emoji: "🇻🇪", name: "Venezuela"),
        CountryFlag(emoji: "🇻🇬", name: "British Virgin Islands"),
        CountryFlag(emoji: "🇻🇮", name: "U.S. Virgin Islands"),
        CountryFlag(emoji: "🇻🇳", name: "Vietnam"),
        CountryFlag(emoji: "🇻🇺", name: "Vanuatu"),
        CountryFlag(emoji: "🇼🇫", name: "Wallis & Futuna"),
        CountryFlag(emoji: "🇼🇸", name: "Samoa"),
        CountryFlag(emoji: "🇽🇰", name: "Kosovo"),
        CountryFlag(emoji: "🇾🇪", name: "Yemen"),
        CountryFlag(emoji: "🇾🇹", name: "Mayotte"),
        CountryFlag(emoji: "🇿🇦", name: "South Africa"),
        CountryFlag(emoji: "🇿🇲", name: "Zambia"),
        CountryFlag(emoji: "🇿🇼", name: "Zimbabwe"),
    ]

    static var all: [CountryFlag] {
        special + countries
    }
}
